### ISSUE TITLE
Path animation with FlatLine

### ISSUE THREAD

**Issue by lslzl3000** [vasturiano/three-globe#17]
I see your comment on path animation with flatline: https://github.com/vasturiano/three-globe/blob/9429f1e42cfe99082ddfa97f8133fc22e663fc9b/src/layers/paths.js#L208

Can we do something to support dashes in flatline? or use different geometry?
e.g. A group of arcs with stroke(TubeGeometry) connected with each other would do a same result as A path, so can we use TubeGeometry in path layer with stroke?

**Comment by vasturiano** [comment]
@lslzl3000 thanks for reaching out.

It's a good question. The current implementation is how far I got while working out the compromises between the different geometry options available for representing an arbitrary 3D path.

So basically,

1. The `FatLine` module currently in use requires a `LineMaterial` in its constructor. This material supports a few dash parameters, but not an _initial gap_ property, as you can see from the [source code](https://github.com/mrdoob/three.js/blob/master/examples/js/lines/LineMaterial.js). Having this property is what allows to have a dash animation because you can just tween this value and doing so build the effect of the dashes moving. So, for dash animation to be supported in FatLines, the material would need to be extended to support this prop. I haven't had the chance to look into how easy/hard would be to do this.

2. One could use a `TubeGeometry` instead of the `FatLine` to render the path, akin to how it's implemented for the [arcs layer](https://vasturiano.github.io/three-globe/example/links/). Animating a dashed material with this geometry is doable as you can [tween the dashOffset uniform in the shader](https://github.com/vasturiano/three-globe/blob/19e9e3ce1180de328db9c22343d8ae55a6d106e8/src/layers/arcs.js#L83-L85). But, the issue with Tube geometries is that it expects the [tubular segments to be of constant lengths](https://threejs.org/docs/#api/en/geometries/TubeGeometry). This makes it difficult to use for a path which is composed of points at variable distance from each other. You'd have to either pick the MCD of all the segment lengths, which could yield a very heavy Tube geometry with too many segments, or sacrifice path resolution by rounding its coordinates. Either is undesirable.

3. A third approach would be to have a separate Tube geometry per dash segment, as you mentioned. I think the geometric complexity of this object would be quite high, introducing a large performance hit. Also, synchronising the dash animations at each of the path vertices (start/end points of each tube) would be rather complicated, specially if each of the tubes has a different number of tubular segments (which would be the whole point in this approach over the 2nd).

As you can see I converged on the current solution after exploring a few alternatives, with the drawback of not being able to animate fat paths. I think the better solution here is still the first option. We only need that `LineMaterial` to support an initial gap parameter.

**Comment by lslzl3000** [comment]
@vasturiano three.js will have updates for LineMaterial very soon, there will  be a new `dashoffset` parameter in shaders to support animation. I have fired an [issue](https://github.com/vasturiano/three-fatline/issues/4) in fatline, please merge updates in this project, thanks

**Comment by vasturiano** [comment]
@lslzl3000 ok with the updated version of `LineMaterial` that supports `dashOffset` I applied the changes that make it support dash animations for fat lines.
Please try with the latest publish version and let me know if it works for you!
