### ISSUE TITLE
Online demos are broken

### ISSUE THREAD

**Issue by OctoD** [vasturiano/three-globe#21]
**Describe the bug**
Every demo does not run

**To Reproduce**
Open an online demo

**Comment by vinayjg** [comment]
Yes. Getting errors at console.

**Comment by vasturiano** [comment]
Thanks for the heads up.

This is due to the recent breaking change in ThreeJs `0.125` to deprecate `Geometry`.
https://discourse.threejs.org/t/three-geometry-will-be-removed-from-core-with-r125/22401/18

For a quick fix I've pinned down the version of Three to `0.124` in the examples, while working on a more permanent fix.
